@startuml 03-example1
start
- счётчик = 0
- Ввод трёх чисел a, b, c
if (a = 0?) then (да)
    - счётчик + 1
endif
if (b = 0?) then (да)
    - счётчик + 1
endif
if (c = 0?) then (да)
    - счётчик + 1
endif
if (счётчик = 2?) then (да)
    - Вывод TRUE
else
    - Вывод FALSE
endif
stop
@enduml
