@startuml 04-example1
start
- i = 0
- res = -1
- Ввод n
while (i < n?) is (да)
    - Ввод числа последовательности
    if (res = -1 и число чётное?) then
    else (да)
        - res = число
    endif
    - счётчик + 1
endwhile
if (res = -1) then
    - Вывод "В последовательности не было чётных чисел"
else (да)
    - Вывод "Первое чётное число в последовательности res"
endif
stop
@enduml
