@startuml 04-example2
start
- res = 0.0
- знак = 1
- элемент = 1.2
- Ввод n
while (i = 0; i < n; i++)
    - Вывод "знак * элемент"
    - res = знак * элемент
    - инвертировать знак
    - увеличить элемент на шаг
endwhile
- Вывод "Сумма n членов последовательности res"
stop
@enduml
