@startuml 05-example4
start
partition #lightGreen "ввод" {
    - Ввод длины массива a (len)
}
partition #lightPink "управление памятью" {
    - Выделить память под массив a
}
partition #lightGreen "ввод" {
    while (i = 0; i < len; i++)
        - Ввод элемента массива a[i]
    endwhile
}
partition #lightGray "вычисления" {
    - j = 0
    while (i = 0; i < len - 1; i++)
        if (a[i] > 0) then
        else (да)
        - j++
        endif
    endwhile
}
partition #lightPink "управление памятью" {
    - Выделить память под массив b (j)
}
partition #lightGray "вычисления" {
    - j = 0
    while (i = 0; i < len - 1; i++)
        if (a[i] > 0) then
        else (да)
        - b[j] = a[i]
        - j++
        endif
    endwhile
}
partition #lightGreen "вывод" {
    - Вывод длины массива b (j)
    while (i = 0; i < j; i++)
        - Вывод элемента массива b[i]
    endwhile
}
partition #lightPink "управление памятью" {
    - Освободить память массивов a, b
}
stop
@enduml
