@startuml 05-example4
start
- Ввод длины массива a (len)
- Выделить память под массив a
while (i = 0; i < len; i++)
    - Ввод элемента массива a[i]
endwhile
- j = 0
while (i = 0; i < len - 1; i++)
    if (a[i] > 0) then
    else (да)
    - j++
    endif
endwhile
- Выделить память под массив b (j)
- j = 0
while (i = 0; i < len - 1; i++)
    if (a[i] > 0) then
    else (да)
    - b[j] = a[i]
    - j++
    endif
endwhile
- Вывод длины массива b (j)
while (i = 0; i < j; i++)
    - Ввод элемента массива b[i]
endwhile
- Освободить память массивов a, b
stop
@enduml
