@startuml 06-example4
start
- Ввод количества строк (n)
- Ввод количества столбцов (m)

- Выделить память под указатели на строки матрицы arr1
while (i = 0; i < n; i++)
    - Выделить память под элементы строки матрицы arr1[i]
endwhile
- Выделить память под указатели на строки матрицы arr2
while (i = 0; i < n; i++)
    - Выделить память под элементы строки матрицы arr2[i]
endwhile
- Выделить память под указатели на строки матрицы res
while (i = 0; i < n; i++)
    - Выделить память под элементы строки матрицы res[i]
endwhile

while (i = 0; i < n; i++)
    while (j = 0; j < m; j++)
        - Ввод элемента матрицы arr1[i][j]
    endwhile
endwhile
while (i = 0; i < n; i++)
    while (j = 0; j < m; j++)
        - Ввод элемента матрицы arr2[i][j]
    endwhile
endwhile

- BEG = m // 3
- END = (m // 3) * 2

while (j = 0; j < m; j++)
    if (BEG <= j < END?) then
        while (i = 0; i < n; i++)
            - res[i][j] = arr2[i][j]
        endwhile
    else (да)
        while (i = 0; i < n; i++)
            - res[i][j] = arr1[i][j]
        endwhile
    endif
endwhile

while (i = 0; i < n; i++)
    while (j = 0; j < m; j++)
        - Вывод элемента матрицы arr[i][j]
    endwhile
endwhile

while (i = 0; i < n; i++)
    - Освободить память вектора элементов строки матрицы arr1[i]
endwhile
- Освободить память вектора указателей на строки матрицы arr1
while (i = 0; i < n; i++)
    - Освободить память вектора элементов строки матрицы arr2[i]
endwhile
- Освободить память вектора указателей на строки матрицы arr2
while (i = 0; i < n; i++)
    - Освободить память вектора элементов строки матрицы res[i]
endwhile
- Освободить память вектора указателей на строки матрицы res
stop
@enduml
