@startuml 07-example2
package "int main()" {
    start
    partition #lightGreen "ввод" {
        - Ввод чисел (a, b)
    }
    partition #lightGray "вычисления" {
        - y = f(a, b)
    }
    partition #lightGreen "вывод" {
        - Вывод результата (y)
    }
    stop
}
package #lightGray "void f(int a, int b, int *res)" {
    start
    - вернуть a ^ 2 + b ^ 2
    stop
}
@enduml
